services:
  api:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=krop
      - POSTGRES_DB=krop
      - POSTGRES_USER=krop